### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by ota-meshi**
I upgraded some dependent packages.

Also, I added some tests to TravisCI's configuration file to check if it works with the old packages.

### CODE REVIEW

**Comment by tpraxl** [comment]
Found this PR because of an own project dependency to `eslint-plugin-vue` that depends on `vue-eslint-parser` and makes `yarn check` fail with:

```
error "eslint-plugin-vue#eslint@^5.0.0" doesn't satisfy found match of "eslint@6.2.2"
error "vue-eslint-parser#eslint@^5.0.0" doesn't satisfy found match of "eslint@6.2.2"
error "eslint-plugin-vue#vue-eslint-parser#eslint@^5.0.0" doesn't satisfy found match of "eslint@6.2.2"
```

Please consider making vue-eslint-parser compatible to eslint 6

**Comment by tpraxl** [comment]
Please merge this PR.

**Comment by sodatea** [comment]
Ping @mysticatea

**Comment by rchl** [comment]
`eslint-plugin-vue` has now upgraded to support eslint 6 and is using this dependency so we get peer dependency warnings because of that.

**Comment by mysticatea** [comment]
Thank you for your contribution and I apologize for the lack of my activity.

**Pull request merged**
