### PR TITLE
Fixed wrong location calculation when including CRLF.

### LINKED ISSUE #50: Expression missing two characters
Hey guys! Very nice library! Found a bug while researching this issue: https://github.com/vuejs/vetur/issues/1319

I'm not familiar with the way parser works. Is there anyone who could take a look at this? Thank you!

Code to reproduce:
```js
const { parse } = require('vue-eslint-parser') 

const templateCode = decodeURI("%3Ctemplate%3E%0D%0A%20%20%20%20%3Cdiv%20@click=%22flag%20=%20false%22%20%3E%0D%0A%20%20%20%20%20%20%20%20%7B%7Bgreeting%7D%7D%0D%0A%20%20%20%20%3C/div%3E%20%20%20%20%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%0A%20%0A%20%0A%3C/template%3E");

const program = parse(templateCode, { sourceType: 'module' });
const handlerExpression = program.templateBody.children[1].startTag.attributes[0].value.expression;
const range = handlerExpression.range;

console.log(templateCode.slice(range[0], range[1]))
```

Expected:
"flag = false"

Actual:
lag = false"

### LINKED ISSUE #59: Some issues about VOnExpression node range when line-breaking style is CRLF.
Hello.
I am using 'eslint-plugin-vue' to do some checking job for my project, but I happened some problems.

Here is the repository for reproducing this problem.
https://github.com/kamilic/reproduce-of-location-problem
In LF, everything runs well, but in CRLF, it seems to go wrong.
(--fix also)

I did some research by reading some source code.
After some code reading, I found that it's not an issues from 'eslint-plugin-vue'. 
The rule `vue/space-infix-ops` is simply a wrapper of eslint rule `space-infix-ops`.

Eslint implements `space-infix-ops` rule depending on ast node range.
https://github.com/eslint/eslint/blob/master/lib/rules/space-infix-ops.js#L55

Estree node range is produced by vue-eslint-parser.

```vue
<template>
    <div @click="a = b"></div>
</template>
```
image

image

I tried to count location manually.
Range of `a` should be [29, 30].
Range of `=` should be [31, 32].
Range of `b` should be [33, 34].

Then, I did some step by step debugging. 
Range still correct before location fixing.
https://github.com/mysticatea/vue-eslint-parser/blob/master/src/script/index.ts#L101
It seem something bad happened in fixLocation method.

Hope it is helpful for fix this issue.

### PR DESCRIPTION
**Pull request by ota-meshi**
This PR fixes an issue with wrong location calculation when the source code contains CRLF.

The problem occurs when the source code is tentatively inserted by this parser to parse directives and there is a `gap` at that location.

Since 22 characters are inserted in v-on parses, this problem seems to occur easily.

---

close #50
close #59

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you for your contribution!

Hmm, it's hard to understand how this patch fixes the problem because my memory about the location calculator is vague 😅. Would you explain the difference between the `shiftOffset` and the `baseOffset`?

**Comment by ota-meshi** [comment]
@mysticatea Thank you for your response!

baseOffset does not calculate gap before this index. In this case, the first index must be the correct index that does not require gap calculations. This can be obtained from the HTML token.

The shiftOffset I added is the offset from the baseOffset. (Sorry that the name is difficult to understand).
Pass the index on the expression string. The expression is the value of the attribute directive or within `{{}}`.

Example:

```vue
  <div
    @click="a=b"
  >
```

This file has line breaks after the `div` and after `"a = b"`. If the line break is `\r\n`, there are 2 gaps.

The location of the "a" identifier is baseOffset. The unnecessary first gap need not be included in the calculation. In order to parse v-on, need to insert `void function($event){` and pass a minus offset of 22 characters. However, since I used to use this -22 index for baseOffset, the first gap will be included in the calculation. shiftOffset was needed to correctly calculate the gap.

**Comment by octref** [comment]
@mysticatea This would help fix issues with Vetur's template checking as well (see the linked issues).

**Comment by tobidalhof** [comment]
@mysticatea please review and merge this PR 😃

**Comment by triforcely** [comment]
@mysticatea can we get this merged?

**Review by mysticatea — APPROVED** [review]
Thank you for your explanation. And I apologize for my delay. I have been lost time for OSS while a time.

LGTM.

**Pull request merged**
