### PR TITLE
Fixed syntax error when function expression on `v-on`.

### PR DESCRIPTION
**Pull request by ota-meshi**
This PR will fix parsing errors reported in https://github.com/vuejs/eslint-plugin-vue/issues/716.

### CODE REVIEW

**Comment by ota-meshi** [comment]
Thank you for checking!

> Please unwrap VOnExpression node if Vue.js doesn't handle it as a statement list.

Is that to build an AST like the following?

code:

```vue
<a @click="function(){ foo(); }">
```

AST on `v-on:click`:

```json
       {
          "type": "VOnExpression",
          "body": [
            {
              "type": "ExpressionStatement",
              "expression": {
                "type": "CallExpression",
                "callee": {
                  "type": "Identifier",
                  "name": "foo"
                },
                "arguments": []
              }
            }
          ]
        }
```

Do you unwrap in the same way for `Arrow Function`?
When unwrapping the `Arrow Function`, AST will be changed.

**Comment by ota-meshi** [comment]
AST of `Arrow Function` is now as follows.

code:

```vue
<a @click="arg => foo();">
```

```json
         {
            "type": "VOnExpression",
            "body": [
              {
                "type": "ExpressionStatement",
                "expression": {
                  "type": "ArrowFunctionExpression",
                  "params": [
                    {
                      "type": "Identifier",
                      "name": "arg"
                    }
                  ],
                  "body": {
                    "type": "CallExpression",
                    "callee": {
                      "type": "Identifier",
                      "name": "foo"
                    },
                    "arguments": []
                  }
                }
              }
            ]
          }
```

**Comment by mysticatea** [comment]
No. I meant to use `parseExpression` simply if it's [function path](https://github.com/vuejs/vue/blob/38e967b8067441ff37cb3b923200023a6b842759/src/compiler/codegen/events.js#L3) or [simple path](https://github.com/vuejs/vue/blob/38e967b8067441ff37cb3b923200023a6b842759/src/compiler/codegen/events.js#L4).

For example:

```html
<a @click="function(arg){ foo(); }">
ExpressionContainer > FunctionExpression

<a @click="arg => foo();">
ExpressionContainer > ArrowFunctionExpression

<a @click="foo">
ExpressionContainer > Identifier

<a @click="foo; bar;">
ExpressionContainer > VOnExpression > ExpressionStatement x 2
```

**Comment by ota-meshi** [comment]
I get it!

**Comment by ota-meshi** [comment]
@mysticatea 
I changed it. Please check again.

**Pull request merged**
