### PR TITLE
feat: Support ESLint 7.x

### LINKED ISSUE #70: Support ESLint 7.x
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

It would be awesome to have official ESLint 7 support. 👊
I'm happy to help where I can of course 🙂

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
Closes #70

### CODE REVIEW

**Comment by mysticatea** [comment]
Thank you for your contribution.

I have a question, why is the breaking change needed to support ESLint 7?

**Comment by MichaelDeBoey** [comment]
@mysticatea ESLint 7 only supports Node@^10.12.x || >=12.x
https://eslint.org/blog/2020/05/eslint-v7.0.0-released#dropping-support-for-node-js-v8
https://eslint.org/docs/user-guide/migrating-to-7.0.0#node-js-8-is-no-longer-supported

**Comment by mysticatea** [comment]
I know it because l have made that change. But, that is not requirements for custom parsers.

**Comment by MichaelDeBoey** [comment]
Then we would probably fix the test in some way, no? 🤔

**Comment by mysticatea** [comment]
Yes. We should not need breaking changes. Let's just confirm the parser works well on ESLint 7.

**Comment by MichaelDeBoey** [comment]
Hmmm really weird that CI keeps failing when I updated the tests 🤔🧐
Can't figure out what's causing the fails though.

**Comment by mysticatea** [comment]
I merged this along with some tweaks: https://github.com/mysticatea/vue-eslint-parser/commit/2df66e426a3b771af2b67b59e8172ad0c29eb5cd

- Update git submodule `/test/fixtures/eslint` to ESLint 7
- Handle new syntax errors in the new minor version of acorn
- Convert bash script in CI to Node.js script for Windows job

Thank you.

**Comment by MichaelDeBoey** [comment]
@mysticatea Any idea when this will be released? 🤔

**Pull request closed without merging**
